### ISSUE TITLE
Visualizing cameras in 3d realtime visualizer

### ISSUE THREAD

**Issue by pablovela5620** [zju3dv/EasyMocap#154]
I currently have a version working that is allowing me to visualize the generated 3d mano mesh, but I've been trying to add cameras (represented as points). But using the extrinsic parameters translation matrixresults that make no sense. Any help would be appreciated. 

I took T_1  `[ -2.5365580108818914e-01, 3.5235992558241717e-02, 1.0070691042108171e+00 ]` and 
          T_2 `[ 2.5316070629630233e-01, 3.3540499529681224e-02, 1.0513487281109317e+00 ]`

and placed them as points in the scene yaml file using `"easymocap.visualize.o3dwrapper.create_point"`

This is what it looks like when I've added in the cameras (should be in front of the mano mesh and seperated, instead they're waaaay in the back and ontop of each other). It feels like an issue with reference frame conversion but I'm not sure exactly what
![3d_viz](https://user-images.githubusercontent.com/25287427/167694529-b08c8582-e981-4244-955a-54bf8e9a4c8a.gif)

This is what the reprojected mesh looks like
![smpl](https://user-images.githubusercontent.com/25287427/167690233-7358f423-b3cd-4c3b-bcbc-cb6ed17b0fc9.gif)

Here is the extri.yml file
```yaml
%YAML:1.0
---
names:
   - "1"
   - "2"
R_1: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 3.5990263448884180e-01, -5.0985984456642497e-01,
       -1.5538521282257671e+00 ]
Rot_1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -5.2538260229794409e-02, 8.5074795696972361e-01,
       -5.2294133984976543e-01, -9.9518386190823849e-01,
       -1.2075401607678921e-03, 9.8018482155991765e-02,
       8.2757550769888916e-02, 5.2557250266599909e-01,
       8.4671407938687782e-01 ]
T_1: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -2.5365580108818914e-01, 3.5235992558241717e-02,
       1.0070691042108171e+00 ]
R_2: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -2.9455174868699907e-01, 1.1151390725401925e-01,
       -1.6272140391559193e+00 ]
Rot_2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -5.2193694519308248e-02, 9.6510653679399616e-01,
       2.5660317786404030e-01, -9.9108970475802249e-01,
       -8.1591073531352920e-02, 1.0528102318393985e-01,
       1.2254393242866432e-01, -2.4882176222649927e-01,
       9.6076569217859698e-01 ]
T_2: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 2.5316070629630233e-01, 3.3540499529681224e-02,
       1.0513487281109317e+00 ]
```

Here is the the scene_yml
```yaml
parent: "config/vis3d/o3d_scene.yml"

width: 960
height: 720

max_human: 1
filter: False

body_model:
  module: "easymocap.smplmodel.body_model.SMPLlayer"
  args:
    _no_merge_: True
    model_path: "data/smplx/smplh/MANO_LEFT.pkl"
    model_type: "mano"
    gender: "neutral"
    device: "cuda"
    regressor_path: "data/smplx/J_regressor_mano_LEFT.txt"

scene:
  _no_merge_: True
  "easymocap.visualize.o3dwrapper.create_coord":
    camera: [-0.5, -0.5, -0.5]
    radius: 0.25
    scale: 1.
  "easymocap.visualize.o3dwrapper.create_bbox":
    min_bound: [-0.5, -0.5, -0.5]
    max_bound: [0.5, 0.5, 0.5]
    flip: False
  "easymocap.visualize.o3dwrapper.create_point":
    points: [[ -2.5365580108818914e-01, 3.5235992558241717e-02,
       -1.0070691042108171e+00 ]]
    r: 0.025
  "easymocap.visualize.o3dwrapper.create_point":
    points: [[ 2.5316070629630233e-01, 3.3540499529681224e-02,
       -1.0513487281109317e+00 ]]
    r: 0.025

camera:
  phi: -90
  theta: 20
  cx: -.25
  cy: 0.0
  cz: 2
```

**Comment by chingswy** [comment]
Hello, the camera position equals to `-R@T` instead of `T`.

**Comment by pablovela5620** [comment]
are you talking about R1 or Rot1 (I think you mean Rot1) as seen below?
```yaml
%YAML:1.0
---
names:
   - "1"
   - "2"
R_1: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 3.5990263448884180e-01, -5.0985984456642497e-01,
       -1.5538521282257671e+00 ]
Rot_1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -5.2538260229794409e-02, 8.5074795696972361e-01,
       -5.2294133984976543e-01, -9.9518386190823849e-01,
       -1.2075401607678921e-03, 9.8018482155991765e-02,
       8.2757550769888916e-02, 5.2557250266599909e-01,
       8.4671407938687782e-01 ]
T_1: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -2.5365580108818914e-01, 3.5235992558241717e-02,
       1.0070691042108171e+00 ]
```
