### ISSUE TITLE
Keypoints annotator release

### ISSUE THREAD

**Issue by tfederico** [zju3dv/EasyMocap#52]
Hello,

thanks for the amazing work!

Are you planning to release the keypoints annotator any time soon?

**Comment by chingswy** [comment]
Sure. Please stay tuned.

**Comment by tfederico** [comment]
@chingswy any update on this?

**Comment by chingswy** [comment]
Please run [this](https://github.com/zju3dv/EasyMocap/blob/master/doc/quickstart.md#1-run-openpose) first which detect the human keypoints by OpenPose.

**Comment by tfederico** [comment]
I managed to run the annotator and got the following info:
```
Here is the help:
------------------
    h:  print the help
    H:  None
    q:  quit the annotation
     :  skip the annotation
    p:  capture the screen
    A:  Automatic running
    z:  continue automatic
    k:  set/unset the key-frame
    w:  Move to last step frame
    a:  Move to last frame
    s:  Move to next step frame
    d:  Move to next frame
    0:  set the bbox ID to 0
    s0:  choose the bbox of ID 0
    1:  set the bbox ID to 1
    s1:  choose the bbox of ID 1
    2:  set the bbox ID to 2
    s2:  choose the bbox of ID 2
    3:  set the bbox ID to 3
    s3:  choose the bbox of ID 3
    4:  set the bbox ID to 4
    s4:  choose the bbox of ID 4
    v:  set the selected joints unvisible
    V:  set the selected joints unvisible if previous unvisible
    f:  set the face unvisible
    c:  check the tracking keypoints
    m:  mirror the keypoints2d
    M:  mirror the keypoints2d of legs and feet
Examples: 
  - noshow r t: automatic removing and tracking
  - noshow nostop r t r c: automatic removing and tracking, if missing, just copy

```

However, it's not very clear to me how I can add keypoints using the annotator if OpenPose was not able to detect them in the first place. I figured that if I click on the center of the bounding box then I can move around the keypoints that are already there, but I don't see how to add new ones.

Do you have any documentation about how to use the annotator?
For example, if I press `k` it should `set/unset the key-frame`, but what do you mean by that?
